from fastapi import FastAPI, File, UploadFile
from fastapi.middleware.cors import CORSMiddleware

app = FastAPI(title="StudyMate AI API")

app.add_middleware(
    CORSMiddleware,
    allow_origins=["http://localhost:5173", "http://127.0.0.1:5173"],
    allow_credentials=True,
    allow_methods=["*"],
    allow_headers=["*"],
)


@app.get("/")
def root():
    return {"message": "StudyMate AI backend is running"}


@app.post("/api/lectures/upload")
async def upload_lecture(file: UploadFile = File(...)):
    return {
        "file_name": file.filename,
        "content_type": file.content_type,
        "notes": [
            "This is a sample note generated by the backend.",
            "Next, we will extract real text from PDF files.",
            "After that, we will connect AI for summaries and quizzes.",
        ],
        "summary": "Sample summary: your upload reached the backend successfully.",
        "key_points": [
            "Frontend can send a file.",
            "Backend can receive a file.",
            "The project foundation is ready.",
        ],
    }
